# Generated by Django 3.1.1 on 2020-09-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horpakdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('water_bill', models.IntegerField()),
                ('fire_bill', models.IntegerField()),
                ('price', models.IntegerField()),
                ('wifi', models.BooleanField(default=True)),
                ('air', models.BooleanField(default=True)),
                ('fan', models.BooleanField(default=True)),
                ('typeMen', models.BooleanField(default=True)),
                ('typeWomen', models.BooleanField(default=True)),
            ],
        ),
    ]
